# TODO: get rid of this https://github.com/markusahlstrand/cloudworker-proxy/issues/127
name: Node.js CI # This is a lie, we are running bun so the CI checks pass

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - run: bun install
      - run: npm run unit
